---
title: 'Codebook: tidydata - generated from UCI HAR dataset'
author: "Vineet Singh"
date: "21 June 2015"
output: html_document
---

# General Description
As part of the coursera getting and cleaning course project work, a tidydata.txt is made from the UCI HAR dataset. This codebook explains the data in the final output file tidydata.txt

The code run_analysis.R creates a the data in required form from the original data retrieved from the url: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

The original dataset comprises six activity performed by thirty subjects giving 561 measurements in total. The script takes the subset of all the variables with names o mean and std and then arranges the data taking average for each subject and each activity, thus having total of 180 observations. final tidy data has 81 variables out of which two are subject and activity, the remaining are the average of variables form original dataset that has mean or std mentioned. Apart form this, the script also cleans the variable renames from the original dataset to have better representation (explained subsequently).

# Varibales Description
## Subject_id
This consists of numeric values form 1 to 30 representing the particular subject who performed the exepriments.

## Activity_labels
The activity labels are the six types of activities performed by the subjects:
- WALKING
- WALKING_UPSTAIRS
- WALKING_DOWNSTAIRS
- SITTING
- STANDING
- LAYING

## Measurements

The names of the measurement for which mean is calculated.
```{r,echo=FALSE}
tidydata <- read.csv("tidydata.txt",header = TRUE,sep = "")
names(tidydata)
```

### Measruement names difference from the original data set
-t and f denote the time series and frequency series.
-Mag was confusing as it could also be understood as magnetometer, so changed to magnitude
-Some elements have BodyBody, this is for the additional vecotrs for the angles.
-this is changed to body_body

